// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chxfdodgxkslycjmgsjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoeGZkb2RneGtzbHljam1nc2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTYxNjUsImV4cCI6MjA2MDE3MjE2NX0.Dkk2b7esVp_EMLEQt0ZI8mieKJXENG1digZWXmxkA3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);